# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

AllCops:
  NewCops: enable

Layout/LineLength:
  Enabled: true
  Max: 120

Metrics/MethodLength:
  Enabled: true
  Max: 20

Metrics/ClassLength:
  Enabled: true
  Max: 150
